const statesOfIndia = [
    { name: 'Andhra Pradesh', id: 1 },
    { name: 'Arunachal Pradesh', id: 2 },
    { name: 'Assam', id: 3 },
    { name: 'Bihar', id: 4 },
    { name: 'Chhattisgarh', id: 5 },
    { name: 'Goa', id: 6 },
    { name: 'Gujarat', id: 7 },
    { name: 'Haryana', id: 8 },
    { name: 'Himachal Pradesh', id: 9 },
    { name: 'Jharkhand', id: 10 },
    { name: 'Karnataka', id: 11 },
    { name: 'Kerala', id: 12 },
    { name: 'Madhya Pradesh', id: 13 },
    { name: 'Maharashtra', id: 14 },
    { name: 'Manipur', id: 15 },
    { name: 'Meghalaya', id: 16 },
    { name: 'Mizoram', id: 17 },
    { name: 'Nagaland', id: 18 },
    { name: 'Odisha', id: 19 },
    { name: 'Punjab', id: 20 },
    { name: 'Rajasthan', id: 21 },
    { name: 'Sikkim', id: 22 },
    { name: 'Tamil Nadu', id: 23 },
    { name: 'Telangana', id: 24 },
    { name: 'Tripura', id: 25 },
    { name: 'Uttar Pradesh', id: 26 },
    { name: 'Uttarakhand', id: 27 },
    { name: 'West Bengal', id: 28 },
    { name: 'Andaman and Nicobar Islands', id: 29 },
    { name: 'Chandigarh', id: 30 },
    { name: 'Dadra and Nagar Haveli and Daman and Diu', id: 31 },
    { name: 'Delhi', id: 32 },
    { name: 'Lakshadweep', id: 33 },
    { name: 'Puducherry', id: 34 },
];
export default statesOfIndia;
